import psycopg2
import bcrypt

conn = psycopg2.connect("postgresql://postgres:postgres@127.0.0.1:5432/creo")
conn.autocommit = True
cur = conn.cursor()

# 1. Purge all test users generated by tests
cur.execute("""
DELETE FROM users
WHERE email LIKE 'client-%'
   OR email LIKE 'spoof-%'
   OR email LIKE 'stale-%'
   OR email LIKE 'replay-%'
   OR email LIKE 'terms-%'
   OR email LIKE 'dna-%'
   OR email LIKE 'pending-%'
   OR email LIKE 'staff-%'
   OR email LIKE 'lead-%'
   OR email LIKE 'admin-%'
   OR email LIKE 'suspend-%'
   OR email LIKE 'editor-%';
""")
print("Purged test junk users.")

# 2. Add realistic client brands with real profiles, plans, and subscriptions
brands = [
    {
        "id": "00000000-0000-0000-0000-000000000005",
        "email": "kavita@astraliving.home",
        "full_name": "Kavita Rao",
        "company_name": "Astra Living",
        "instagram_username": "astraliving.home",
        "brand_summary": "Minimalist Scandinavian interior aesthetics with natural sunlight and architectural negative space.",
        "plan_name": "growth",
        "stage": 5,
        "quota": {"static_post": (15, 6), "reel": (8, 4), "story": (20, 11)}
    },
    {
        "id": "00000000-0000-0000-0000-000000000006",
        "email": "meera@urbanbakes.in",
        "full_name": "Meera Krishnan",
        "company_name": "Urban Bakes",
        "instagram_username": "urbanbakes.in",
        "brand_summary": "Artisanal sourdough, French viennoiserie, and community bakery workshops in Bangalore.",
        "plan_name": "starter",
        "stage": 5,
        "quota": {"static_post": (8, 3), "reel": (4, 2), "story": (10, 5)}
    },
    {
        "id": "00000000-0000-0000-0000-000000000007",
        "email": "vikram@zenithfitness.in",
        "full_name": "Vikram Singhania",
        "company_name": "Zenith Fitness",
        "instagram_username": "zenithfitness.club",
        "brand_summary": "High-performance athletic conditioning, Olympic lifting, and science-backed recovery gym chain.",
        "plan_name": "pro",
        "stage": 5,
        "quota": {"static_post": (30, 12), "reel": (16, 7), "story": (40, 19)}
    },
    {
        "id": "00000000-0000-0000-0000-000000000008",
        "email": "arjun@kayabotanicals.com",
        "full_name": "Arjun Kapoor",
        "company_name": "Kaya Botanicals",
        "instagram_username": "kayabotanicals",
        "brand_summary": "Ayurvedic clinical skincare formulated with Himalayan wildcrafted active botanicals.",
        "plan_name": "growth",
        "stage": 4,
        "quota": {"static_post": (15, 4), "reel": (8, 3), "story": (20, 8)}
    },
    {
        "id": "00000000-0000-0000-0000-000000000009",
        "email": "ananya@heritagelooms.com",
        "full_name": "Ananya Sen",
        "company_name": "Heritage Looms",
        "instagram_username": "heritagelooms.india",
        "brand_summary": "Handwoven Chanderi, Banarasi silk, and sustainable luxury heritage apparel.",
        "plan_name": "pro",
        "stage": 5,
        "quota": {"static_post": (30, 14), "reel": (16, 9), "story": (40, 22)}
    }
]

pw_hash = bcrypt.hashpw(b"CreoAdmin2026!", bcrypt.gensalt()).decode("utf-8")

# Get plan IDs
cur.execute("SELECT name, id FROM plans;")
plan_map = {row[0]: row[1] for row in cur.fetchall()}

for b in brands:
    cur.execute("""
    INSERT INTO users (id, auth_id, email, full_name, hashed_password, role, account_status, email_verified_at)
    VALUES (%s, %s, %s, %s, %s, 'client', 'active', NOW())
    ON CONFLICT (id) DO UPDATE SET
        email = EXCLUDED.email,
        full_name = EXCLUDED.full_name,
        hashed_password = EXCLUDED.hashed_password,
        account_status = 'active';
    """, (b["id"], f"auth-client-{b['id'][-3:]}", b["email"], b["full_name"], pw_hash))

    cur.execute("""
    INSERT INTO client_profiles (user_id, company_name, instagram_username, brand_summary, terms_accepted_at, onboarding_completed_at)
    VALUES (%s, %s, %s, %s, NOW() - INTERVAL '30 days', NOW() - INTERVAL '28 days')
    ON CONFLICT (user_id) DO UPDATE SET
        company_name = EXCLUDED.company_name,
        instagram_username = EXCLUDED.instagram_username,
        brand_summary = EXCLUDED.brand_summary;
    """, (b["id"], b["company_name"], b["instagram_username"], b["brand_summary"]))

    plan_id = plan_map.get(b["plan_name"])
    plan_amounts = {"starter": 25000.00, "growth": 50000.00, "pro": 95000.00}
    amt = plan_amounts.get(b["plan_name"], 50000.00)
    if plan_id:
        cur.execute("""
        INSERT INTO subscriptions (id, client_id, plan_id, status, gateway, amount, current_period_start, current_period_end)
        VALUES (gen_random_uuid(), %s, %s, 'active', 'razorpay', %s, DATE_TRUNC('month', CURRENT_DATE)::DATE, (DATE_TRUNC('month', CURRENT_DATE) + INTERVAL '1 month - 1 day')::DATE)
        ON CONFLICT DO NOTHING;
        """, (b["id"], plan_id, amt))

    # Seed usage counters
    for kind, (quota, used) in b["quota"].items():
        cur.execute("""
        INSERT INTO usage_counters (id, client_id, period_start, period_end, kind, quota, used)
        VALUES (gen_random_uuid(), %s, DATE_TRUNC('month', CURRENT_DATE)::DATE, (DATE_TRUNC('month', CURRENT_DATE) + INTERVAL '1 month - 1 day')::DATE, %s, %s, %s)
        ON CONFLICT (client_id, period_start, kind) DO UPDATE SET
            quota = EXCLUDED.quota,
            used = EXCLUDED.used;
        """, (b["id"], kind, quota, used))

# Also refresh the materialized view!
try:
    cur.execute("REFRESH MATERIALIZED VIEW CONCURRENTLY mv_exec_kpis;")
except Exception:
    cur.execute("REFRESH MATERIALIZED VIEW mv_exec_kpis;")

print("Real brands populated and materialized view refreshed!")
cur.close()
conn.close()
