"""add_is_rejection_reason

Revision ID: 020
Revises: 019
Create Date: 2026-06-16 19:18:25.783056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c571fe7a6082"
down_revision = "019"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addon_pricing', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('content_calendar', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_content_calendar_linked_task_id'), 'content_calendar', ['linked_task_id'], unique=False)
    op.alter_column('content_plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_content_plans_month_year'), table_name='content_plans')
    op.create_index(op.f('ix_content_plans_month'), 'content_plans', ['month'], unique=False)
    op.create_index(op.f('ix_content_plans_year'), 'content_plans', ['year'], unique=False)
    op.alter_column('custom_pricing', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.execute("ALTER TABLE deliverable_comments ADD COLUMN IF NOT EXISTS is_rejection_reason BOOLEAN NOT NULL DEFAULT false")
    op.alter_column('deliverables', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_deliverables_parent_deliverable_id'), table_name='deliverables')
    op.alter_column('escalations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('leave_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('questionnaires', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('questionnaires_user_id_key'), 'questionnaires', type_='unique')
    op.drop_index(op.f('ix_questionnaires_user_id'), table_name='questionnaires')
    op.create_index(op.f('ix_questionnaires_user_id'), 'questionnaires', ['user_id'], unique=True)
    op.alter_column('subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('team_members', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('team_members_user_id_key'), 'team_members', type_='unique')
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('team_members_user_id_key'), 'team_members', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('team_members', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_questionnaires_user_id'), table_name='questionnaires')
    op.create_index(op.f('ix_questionnaires_user_id'), 'questionnaires', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('questionnaires_user_id_key'), 'questionnaires', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('questionnaires', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('leave_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('escalations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_deliverables_parent_deliverable_id'), 'deliverables', ['parent_deliverable_id'], unique=False)
    op.alter_column('deliverables', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('deliverable_comments', 'is_rejection_reason')
    op.alter_column('custom_pricing', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_content_plans_year'), table_name='content_plans')
    op.drop_index(op.f('ix_content_plans_month'), table_name='content_plans')
    op.create_index(op.f('ix_content_plans_month_year'), 'content_plans', ['month', 'year'], unique=False)
    op.alter_column('content_plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_content_calendar_linked_task_id'), table_name='content_calendar')
    op.alter_column('content_calendar', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('addon_pricing', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
