"""multi_tenant_schema

Revision ID: c71a2fc5b835
Revises: 0008_calendar_sequencing
Create Date: 2026-09-20 12:26:38.554468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c71a2fc5b835'
down_revision: Union[str, None] = '0008_calendar_sequencing'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('plan_tier', sa.String(length=30), nullable=False),
    sa.Column('max_clients', sa.Integer(), nullable=False),
    sa.Column('max_staff', sa.Integer(), nullable=False),
    sa.Column('branding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_domain'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('platform_payment_events',
    sa.Column('provider', postgresql.ENUM('razorpay', 'stripe', 'manual', name='payment_provider', create_type=False), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_platform_payment_event')
    )
    op.create_index('idx_platform_payment_events_unprocessed', 'platform_payment_events', ['received_at'], unique=False, postgresql_where=sa.text('processed_at IS NULL'))
    op.create_table('teams',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'name', name='uq_team_name')
    )
    op.create_table('client_role_requirements',
    sa.Column('agency_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('craft_role', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id', 'craft_role')
    )
    op.create_index(op.f('ix_client_role_requirements_agency_id'), 'client_role_requirements', ['agency_id'], unique=False)
    op.create_table('platform_subscriptions',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('trialing', 'active', 'past_due', 'canceled', 'incomplete', name='subscription_status', create_type=False), nullable=False),
    sa.Column('gateway', postgresql.ENUM('razorpay', 'stripe', 'manual', name='payment_provider', create_type=False), nullable=False),
    sa.Column('gateway_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_customer_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id')
    )
    op.create_table('team_members',
    sa.Column('agency_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    op.create_index(op.f('ix_team_members_agency_id'), 'team_members', ['agency_id'], unique=False)
    op.add_column('announcements', sa.Column('agency_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_announcements_agency_id'), 'announcements', ['agency_id'], unique=False)
    op.create_foreign_key(None, 'announcements', 'agencies', ['agency_id'], ['id'], ondelete='CASCADE')
    op.add_column('audit_log', sa.Column('agency_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_audit_log_agency_id'), 'audit_log', ['agency_id'], unique=False)
    op.create_foreign_key(None, 'audit_log', 'agencies', ['agency_id'], ['id'], ondelete='CASCADE')
    op.add_column('calendar_blackouts', sa.Column('agency_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_calendar_blackouts_agency_id'), 'calendar_blackouts', ['agency_id'], unique=False)
    op.create_foreign_key(None, 'calendar_blackouts', 'agencies', ['agency_id'], ['id'], ondelete='CASCADE')
    op.add_column('calendar_policies', sa.Column('agency_id', sa.UUID(), nullable=True))
    op.alter_column('calendar_policies', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'niche_template'::text"))
    op.create_index(op.f('ix_calendar_policies_agency_id'), 'calendar_policies', ['agency_id'], unique=False)
    op.create_foreign_key(None, 'calendar_policies', 'agencies', ['agency_id'], ['id'], ondelete='CASCADE')
    op.add_column('client_assignments', sa.Column('agency_id', sa.UUID(), nullable=True))
    op.add_column('client_assignments', sa.Column('craft_role', sa.String(length=30), nullable=True))
    op.execute("UPDATE client_assignments SET craft_role = SUBSTRING(COALESCE(role, 'graphic_designer'), 1, 30) WHERE craft_role IS NULL")
    op.execute("""
        DELETE FROM client_assignments
        WHERE id IN (
            SELECT id FROM (
                SELECT id, ROW_NUMBER() OVER (
                    PARTITION BY client_id, craft_role 
                    ORDER BY is_primary DESC, created_at DESC
                ) as rn
                FROM client_assignments
            ) t WHERE t.rn > 1
        )
    """)
    op.alter_column('client_assignments', 'craft_role', nullable=False)
    op.add_column('client_assignments', sa.Column('points_committed', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.alter_column('client_assignments', 'points_committed', server_default=None)
    op.add_column('client_assignments', sa.Column('from_team_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('idx_assignments_user'), table_name='client_assignments', if_exists=True)
    op.create_index(op.f('ix_client_assignments_agency_id'), 'client_assignments', ['agency_id'], unique=False)
    op.create_index('uq_one_person_per_craft', 'client_assignments', ['client_id', 'craft_role'], unique=True)
    op.create_foreign_key(None, 'client_assignments', 'teams', ['from_team_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'client_assignments', 'agencies', ['agency_id'], ['id'], ondelete='CASCADE')
    op.add_column('client_cycles', sa.Column('agency_id', sa.UUID(), nullable=True))
    op.alter_column('client_cycles', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::text"))
    op.create_index(op.f('ix_client_cycles_agency_id'), 'client_cycles', ['agency_id'], unique=False)
    op.create_foreign_key(None, 'client_cycles', 'agencies', ['agency_id'], ['id'], ondelete='CASCADE')
    op.add_column('content_calendar', sa.Column('agency_id', sa.UUID(), nullable=True))
    op.alter_column('content_calendar', 'daypart',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('content_calendar', 'phase',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'B'::text"))
    op.alter_column('content_calendar', 'funnel_stage',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'reach'::text"))
    op.alter_column('content_calendar', 'slot_source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'original'::text"))
    op.alter_column('content_calendar', 'story_role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_index(op.f('idx_calendar_client'), table_name='content_calendar', if_exists=True)
    op.drop_index(op.f('idx_calendar_date'), table_name='content_calendar', if_exists=True)
    op.create_index(op.f('ix_content_calendar_agency_id'), 'content_calendar', ['agency_id'], unique=False)
    op.create_index(op.f('ix_content_calendar_client_id'), 'content_calendar', ['client_id'], unique=False)
    op.create_foreign_key(None, 'content_calendar', 'agencies', ['agency_id'], ['id'], ondelete='CASCADE')
    op.add_column('deliverables', sa.Column('agency_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('idx_deliv_client'), table_name='deliverables', if_exists=True)
    op.drop_index(op.f('idx_deliverables_approved_turnaround'), table_name='deliverables', postgresql_where="((status = ANY (ARRAY['approved'::deliverable_status, 'published'::deliverable_status])) AND (approved_at IS NOT NULL))", if_exists=True)
    op.create_index(op.f('ix_deliverables_agency_id'), 'deliverables', ['agency_id'], unique=False)
    op.create_index(op.f('ix_deliverables_client_id'), 'deliverables', ['client_id'], unique=False)
    op.create_index(op.f('ix_deliverables_root_id'), 'deliverables', ['root_id'], unique=False)
    op.create_index(op.f('ix_deliverables_status'), 'deliverables', ['status'], unique=False)
    op.create_foreign_key(None, 'deliverables', 'agencies', ['agency_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_idempotency_expires'), table_name='idempotency_keys', if_exists=True)
    op.add_column('leave_requests', sa.Column('agency_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('idx_leave_dates'), table_name='leave_requests', if_exists=True)
    op.drop_index(op.f('idx_leave_user'), table_name='leave_requests', if_exists=True)
    op.create_index(op.f('ix_leave_requests_agency_id'), 'leave_requests', ['agency_id'], unique=False)
    op.create_foreign_key(None, 'leave_requests', 'agencies', ['agency_id'], ['id'], ondelete='CASCADE')
    op.add_column('notifications', sa.Column('agency_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_notifications_agency_id'), 'notifications', ['agency_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'agencies', ['agency_id'], ['id'], ondelete='CASCADE')
    op.add_column('plans', sa.Column('agency_id', sa.UUID(), nullable=True))
    op.alter_column('plans', 'currency',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'INR'::bpchar"))
    op.execute("ALTER TABLE plans DROP CONSTRAINT IF EXISTS plans_name_key")
    op.create_index(op.f('ix_plans_agency_id'), 'plans', ['agency_id'], unique=False)
    op.create_foreign_key(None, 'plans', 'agencies', ['agency_id'], ['id'], ondelete='CASCADE')
    op.add_column('questionnaires', sa.Column('agency_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('idx_questionnaires_user'), table_name='questionnaires', if_exists=True)
    op.create_index(op.f('ix_questionnaires_agency_id'), 'questionnaires', ['agency_id'], unique=False)
    op.create_index(op.f('ix_questionnaires_user_id'), 'questionnaires', ['user_id'], unique=False)
    op.create_foreign_key(None, 'questionnaires', 'agencies', ['agency_id'], ['id'], ondelete='CASCADE')
    op.add_column('shoot_days', sa.Column('agency_id', sa.UUID(), nullable=True))
    op.alter_column('shoot_days', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'proposed'::text"))
    op.create_index(op.f('ix_shoot_days_agency_id'), 'shoot_days', ['agency_id'], unique=False)
    op.create_foreign_key(None, 'shoot_days', 'agencies', ['agency_id'], ['id'], ondelete='CASCADE')
    op.add_column('staff_profiles', sa.Column('agency_id', sa.UUID(), nullable=True))
    op.add_column('staff_profiles', sa.Column('craft_role', sa.String(length=30), nullable=True))
    op.execute("""
        UPDATE staff_profiles sp
        SET craft_role = CASE
            WHEN u.role::text = 'video_editor' THEN 'video_editor'
            WHEN u.role::text = 'team_lead' THEN 'team_lead'
            WHEN u.role::text = 'copywriter' THEN 'copywriter'
            ELSE 'graphic_designer'
        END
        FROM users u
        WHERE sp.user_id = u.id AND sp.craft_role IS NULL
    """)
    op.execute("UPDATE staff_profiles SET craft_role = 'graphic_designer' WHERE craft_role IS NULL")
    op.alter_column('staff_profiles', 'craft_role', nullable=False)
    op.add_column('staff_profiles', sa.Column('monthly_points', sa.Integer(), nullable=False, server_default=sa.text('100')))
    op.alter_column('staff_profiles', 'monthly_points', server_default=None)
    op.alter_column('staff_profiles', 'skills',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('staff_profiles', 'sub_skills',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.create_index(op.f('ix_staff_profiles_agency_id'), 'staff_profiles', ['agency_id'], unique=False)
    op.create_foreign_key(None, 'staff_profiles', 'agencies', ['agency_id'], ['id'], ondelete='CASCADE')
    op.add_column('subscriptions', sa.Column('agency_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('idx_subscriptions_plan'), table_name='subscriptions', if_exists=True)
    op.create_index(op.f('ix_subscriptions_agency_id'), 'subscriptions', ['agency_id'], unique=False)
    op.create_foreign_key(None, 'subscriptions', 'agencies', ['agency_id'], ['id'], ondelete='CASCADE')
    op.add_column('tasks', sa.Column('agency_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('idx_tasks_assigned'), table_name='tasks', if_exists=True)
    op.drop_index(op.f('idx_tasks_client'), table_name='tasks', if_exists=True)
    op.drop_index(op.f('idx_tasks_kanban'), table_name='tasks', if_exists=True)
    op.drop_index(op.f('idx_tasks_sla'), table_name='tasks', postgresql_where="(status <> ALL (ARRAY['ready_to_publish'::task_status, 'completed'::task_status]))", if_exists=True)
    op.drop_index(op.f('idx_tasks_status'), table_name='tasks', if_exists=True)
    op.drop_index(op.f('idx_tasks_window'), table_name='tasks', postgresql_where="(status = ANY (ARRAY['in_production'::task_status, 'internal_qa'::task_status]))", if_exists=True)
    op.create_index(op.f('ix_tasks_agency_id'), 'tasks', ['agency_id'], unique=False)
    op.create_index(op.f('ix_tasks_assigned_to'), 'tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_tasks_client_id'), 'tasks', ['client_id'], unique=False)
    op.create_index(op.f('ix_tasks_sla_due_at'), 'tasks', ['sla_due_at'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_foreign_key(None, 'tasks', 'agencies', ['agency_id'], ['id'], ondelete='CASCADE')
    op.add_column('ticket_messages', sa.Column('agency_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('idx_ticket_messages_ticket'), table_name='ticket_messages', if_exists=True)
    op.create_index(op.f('ix_ticket_messages_agency_id'), 'ticket_messages', ['agency_id'], unique=False)
    op.create_index(op.f('ix_ticket_messages_ticket_id'), 'ticket_messages', ['ticket_id'], unique=False)
    op.create_foreign_key(None, 'ticket_messages', 'agencies', ['agency_id'], ['id'], ondelete='CASCADE')
    op.execute("ALTER TABLE tickets ADD COLUMN IF NOT EXISTS agency_id UUID")
    op.execute("ALTER TABLE tickets ADD COLUMN IF NOT EXISTS deliverable_id UUID")
    op.drop_index(op.f('idx_tickets_client'), table_name='tickets', if_exists=True)
    op.drop_index(op.f('idx_tickets_status'), table_name='tickets', if_exists=True)
    op.execute("CREATE INDEX IF NOT EXISTS ix_tickets_agency_id ON tickets (agency_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_tickets_client_id ON tickets (client_id)")
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tickets_deliverable_id_fkey') THEN
                ALTER TABLE tickets ADD CONSTRAINT tickets_deliverable_id_fkey
                FOREIGN KEY (deliverable_id) REFERENCES deliverables(id) ON DELETE SET NULL;
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tickets_agency_id_fkey') THEN
                ALTER TABLE tickets ADD CONSTRAINT tickets_agency_id_fkey
                FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE CASCADE;
            END IF;
        END $$;
    """)
    op.execute("ALTER TABLE usage_counters ADD COLUMN IF NOT EXISTS agency_id UUID")
    op.execute("CREATE INDEX IF NOT EXISTS ix_usage_counters_agency_id ON usage_counters (agency_id)")
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'usage_counters_agency_id_fkey') THEN
                ALTER TABLE usage_counters ADD CONSTRAINT usage_counters_agency_id_fkey
                FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE CASCADE;
            END IF;
        END $$;
    """)
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS agency_id UUID")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS owning_team_id UUID")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS must_reset_password BOOLEAN DEFAULT FALSE NOT NULL")
    op.drop_index(op.f('idx_users_email'), table_name='users', if_exists=True)
    op.drop_index(op.f('idx_users_role'), table_name='users', if_exists=True)
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS users_auth_id_key")
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS users_email_key")
    op.execute("CREATE INDEX IF NOT EXISTS idx_users_agency ON users (agency_id, role, created_at)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_users_role_created_at ON users (role, created_at)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_users_agency_id ON users (agency_id)")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_users_auth_id ON users (auth_id)")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email ON users (email)")
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_owning_team_id_fkey') THEN
                ALTER TABLE users ADD CONSTRAINT users_owning_team_id_fkey
                FOREIGN KEY (owning_team_id) REFERENCES teams(id) ON DELETE SET NULL;
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_agency_id_fkey') THEN
                ALTER TABLE users ADD CONSTRAINT users_agency_id_fkey
                FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE CASCADE;
            END IF;
        END $$;
    """)

    # Ensure default primary agency exists and backfill agency_id for existing records
    op.execute("""
        DO $$
        DECLARE
            default_agency_id UUID;
        BEGIN
            INSERT INTO agencies (id, name, slug, status, plan_tier, max_clients, max_staff, branding, timezone)
            VALUES ('00000000-0000-0000-0000-000000000001', 'Creo Digital', 'creo', 'active', 'enterprise', 100, 100, '{}'::jsonb, 'Asia/Kolkata')
            ON CONFLICT (slug) DO NOTHING;

            SELECT id INTO default_agency_id FROM agencies WHERE slug = 'creo' LIMIT 1;

            IF default_agency_id IS NOT NULL THEN
                UPDATE users SET agency_id = default_agency_id WHERE agency_id IS NULL;
                UPDATE deliverables SET agency_id = default_agency_id WHERE agency_id IS NULL;
                UPDATE tasks SET agency_id = default_agency_id WHERE agency_id IS NULL;
                UPDATE content_calendar SET agency_id = default_agency_id WHERE agency_id IS NULL;
                UPDATE subscriptions SET agency_id = default_agency_id WHERE agency_id IS NULL;
                UPDATE plans SET agency_id = default_agency_id WHERE agency_id IS NULL;
                UPDATE staff_profiles SET agency_id = default_agency_id WHERE agency_id IS NULL;
                UPDATE client_assignments SET agency_id = default_agency_id WHERE agency_id IS NULL;
                UPDATE tickets SET agency_id = default_agency_id WHERE agency_id IS NULL;
                UPDATE ticket_messages SET agency_id = default_agency_id WHERE agency_id IS NULL;
                UPDATE announcements SET agency_id = default_agency_id WHERE agency_id IS NULL;
                UPDATE audit_log SET agency_id = default_agency_id WHERE agency_id IS NULL;
                UPDATE questionnaires SET agency_id = default_agency_id WHERE agency_id IS NULL;
                UPDATE usage_counters SET agency_id = default_agency_id WHERE agency_id IS NULL;
                UPDATE client_cycles SET agency_id = default_agency_id WHERE agency_id IS NULL;
                UPDATE calendar_policies SET agency_id = default_agency_id WHERE agency_id IS NULL;
                UPDATE shoot_days SET agency_id = default_agency_id WHERE agency_id IS NULL;
                UPDATE leave_requests SET agency_id = default_agency_id WHERE agency_id IS NULL;
                UPDATE calendar_blackouts SET agency_id = default_agency_id WHERE agency_id IS NULL;
            END IF;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'users', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_auth_id'), table_name='users')
    op.drop_index(op.f('ix_users_agency_id'), table_name='users')
    op.drop_index('idx_users_role_created_at', table_name='users')
    op.drop_index('idx_users_agency', table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_auth_id_key'), 'users', ['auth_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.drop_column('users', 'must_reset_password')
    op.drop_column('users', 'owning_team_id')
    op.drop_column('users', 'agency_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'usage_counters', type_='foreignkey')
    op.drop_index(op.f('ix_usage_counters_agency_id'), table_name='usage_counters')
    op.drop_column('usage_counters', 'agency_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_tickets_client_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_agency_id'), table_name='tickets')
    op.create_index(op.f('idx_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('idx_tickets_client'), 'tickets', ['client_id'], unique=False)
    op.drop_column('tickets', 'deliverable_id')
    op.drop_column('tickets', 'agency_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'ticket_messages', type_='foreignkey')
    op.drop_index(op.f('ix_ticket_messages_ticket_id'), table_name='ticket_messages')
    op.drop_index(op.f('ix_ticket_messages_agency_id'), table_name='ticket_messages')
    op.create_index(op.f('idx_ticket_messages_ticket'), 'ticket_messages', ['ticket_id'], unique=False)
    op.drop_column('ticket_messages', 'agency_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_sla_due_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_client_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_agency_id'), table_name='tasks')
    op.create_index(op.f('idx_tasks_window'), 'tasks', ['assigned_to', 'due_date'], unique=False, postgresql_where="(status = ANY (ARRAY['in_production'::task_status, 'internal_qa'::task_status]))")
    op.create_index(op.f('idx_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('idx_tasks_sla'), 'tasks', ['status', 'sla_due_at'], unique=False, postgresql_where="(status <> ALL (ARRAY['ready_to_publish'::task_status, 'completed'::task_status]))")
    op.create_index(op.f('idx_tasks_kanban'), 'tasks', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_tasks_client'), 'tasks', ['client_id'], unique=False)
    op.create_index(op.f('idx_tasks_assigned'), 'tasks', ['assigned_to'], unique=False)
    op.drop_column('tasks', 'agency_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_index(op.f('ix_subscriptions_agency_id'), table_name='subscriptions')
    op.create_index(op.f('idx_subscriptions_plan'), 'subscriptions', ['plan_id'], unique=False)
    op.drop_column('subscriptions', 'agency_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'staff_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_staff_profiles_agency_id'), table_name='staff_profiles')
    op.alter_column('staff_profiles', 'sub_skills',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('staff_profiles', 'skills',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_column('staff_profiles', 'monthly_points')
    op.drop_column('staff_profiles', 'craft_role')
    op.drop_column('staff_profiles', 'agency_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'shoot_days', type_='foreignkey')
    op.drop_index(op.f('ix_shoot_days_agency_id'), table_name='shoot_days')
    op.alter_column('shoot_days', 'status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'proposed'::text"))
    op.drop_column('shoot_days', 'agency_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'questionnaires', type_='foreignkey')
    op.drop_index(op.f('ix_questionnaires_user_id'), table_name='questionnaires')
    op.drop_index(op.f('ix_questionnaires_agency_id'), table_name='questionnaires')
    op.create_index(op.f('idx_questionnaires_user'), 'questionnaires', ['user_id'], unique=False)
    op.drop_column('questionnaires', 'agency_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'plans', type_='foreignkey')
    op.drop_index(op.f('ix_plans_agency_id'), table_name='plans')
    op.create_unique_constraint(op.f('plans_name_key'), 'plans', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('plans', 'currency',
               existing_type=sa.String(length=3),
               type_=sa.CHAR(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'INR'::bpchar"))
    op.drop_column('plans', 'agency_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_agency_id'), table_name='notifications')
    op.drop_column('notifications', 'agency_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.drop_index(op.f('ix_leave_requests_agency_id'), table_name='leave_requests')
    op.create_index(op.f('idx_leave_user'), 'leave_requests', ['user_id'], unique=False)
    op.create_index(op.f('idx_leave_dates'), 'leave_requests', ['start_date', 'end_date'], unique=False)
    op.drop_column('leave_requests', 'agency_id')
    op.create_index(op.f('idx_idempotency_expires'), 'idempotency_keys', ['expires_at'], unique=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'deliverables', type_='foreignkey')
    op.drop_index(op.f('ix_deliverables_status'), table_name='deliverables')
    op.drop_index(op.f('ix_deliverables_root_id'), table_name='deliverables')
    op.drop_index(op.f('ix_deliverables_client_id'), table_name='deliverables')
    op.drop_index(op.f('ix_deliverables_agency_id'), table_name='deliverables')
    op.create_index(op.f('idx_deliverables_approved_turnaround'), 'deliverables', ['status', 'approved_at', 'created_at'], unique=False, postgresql_where="((status = ANY (ARRAY['approved'::deliverable_status, 'published'::deliverable_status])) AND (approved_at IS NOT NULL))")
    op.create_index(op.f('idx_deliv_client'), 'deliverables', ['client_id'], unique=False)
    op.drop_column('deliverables', 'agency_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'content_calendar', type_='foreignkey')
    op.drop_index(op.f('ix_content_calendar_client_id'), table_name='content_calendar')
    op.drop_index(op.f('ix_content_calendar_agency_id'), table_name='content_calendar')
    op.create_index(op.f('idx_calendar_date'), 'content_calendar', ['publish_date'], unique=False)
    op.create_index(op.f('idx_calendar_client'), 'content_calendar', ['client_id'], unique=False)
    op.alter_column('content_calendar', 'story_role',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('content_calendar', 'slot_source',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'original'::text"))
    op.alter_column('content_calendar', 'funnel_stage',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'reach'::text"))
    op.alter_column('content_calendar', 'phase',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'B'::text"))
    op.alter_column('content_calendar', 'daypart',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('content_calendar', 'agency_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'client_cycles', type_='foreignkey')
    op.drop_index(op.f('ix_client_cycles_agency_id'), table_name='client_cycles')
    op.alter_column('client_cycles', 'status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::text"))
    op.drop_column('client_cycles', 'agency_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'client_assignments', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'client_assignments', type_='foreignkey')
    op.drop_index('uq_one_person_per_craft', table_name='client_assignments')
    op.drop_index(op.f('ix_client_assignments_agency_id'), table_name='client_assignments')
    op.create_index(op.f('idx_assignments_user'), 'client_assignments', ['user_id'], unique=False)
    op.drop_column('client_assignments', 'from_team_id')
    op.drop_column('client_assignments', 'points_committed')
    op.drop_column('client_assignments', 'craft_role')
    op.drop_column('client_assignments', 'agency_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'calendar_policies', type_='foreignkey')
    op.drop_index(op.f('ix_calendar_policies_agency_id'), table_name='calendar_policies')
    op.alter_column('calendar_policies', 'source',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'niche_template'::text"))
    op.drop_column('calendar_policies', 'agency_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'calendar_blackouts', type_='foreignkey')
    op.drop_index(op.f('ix_calendar_blackouts_agency_id'), table_name='calendar_blackouts')
    op.drop_column('calendar_blackouts', 'agency_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'audit_log', type_='foreignkey')
    op.drop_index(op.f('ix_audit_log_agency_id'), table_name='audit_log')
    op.drop_column('audit_log', 'agency_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'announcements', type_='foreignkey')
    op.drop_index(op.f('ix_announcements_agency_id'), table_name='announcements')
    op.drop_column('announcements', 'agency_id')
    op.drop_index(op.f('ix_team_members_agency_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_table('platform_subscriptions')
    op.drop_index(op.f('ix_client_role_requirements_agency_id'), table_name='client_role_requirements')
    op.drop_table('client_role_requirements')
    op.drop_table('teams')
    op.drop_index('idx_platform_payment_events_unprocessed', table_name='platform_payment_events', postgresql_where=sa.text('processed_at IS NULL'))
    op.drop_table('platform_payment_events')
    op.drop_table('agencies')
    # ### end Alembic commands ###
