"""Catch up any missing columns

Revision ID: 9ddd8537d7d4
Revises: 4e4b0885fa87
Create Date: 2026-08-10 21:37:30.266870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ddd8537d7d4'
down_revision: Union[str, Sequence[str], None] = '4e4b0885fa87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questionnaire_audit_logs_questionnaire_id'), table_name='questionnaire_audit_logs')
    op.drop_table('questionnaire_audit_logs')
    op.drop_index(op.f('ix_task_status_history_task_id'), table_name='task_status_history')
    op.drop_table('task_status_history')
    op.add_column('addon_pricing', sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'addon_pricing', 'users', ['updated_by'], ['id'])
    op.add_column('addons', sa.Column('client_id', sa.UUID(as_uuid=False), nullable=False))
    op.add_column('addons', sa.Column('gateway_payment_id', sa.Text(), nullable=True))
    op.add_column('addons', sa.Column('content_brief', sa.Text(), nullable=True))
    op.add_column('addons', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('addons', 'gateway',
               existing_type=postgresql.ENUM('razorpay', 'stripe', name='payment_gateway'),
               nullable=False)
    op.drop_index(op.f('ix_addons_user_id'), table_name='addons')
    op.drop_index(op.f('ix_addons_user_id_status'), table_name='addons')
    op.create_index(op.f('ix_addons_client_id'), 'addons', ['client_id'], unique=False)
    op.drop_constraint(op.f('addons_user_id_fkey'), 'addons', type_='foreignkey')
    op.create_foreign_key(None, 'addons', 'users', ['client_id'], ['id'])
    op.drop_column('addons', 'payment_id')
    op.drop_column('addons', 'user_id')
    op.drop_index(op.f('ix_content_calendar_client_id_scheduled_date'), table_name='content_calendar')
    op.alter_column('custom_pricing', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('custom_pricing', 'requested_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_custom_pricing_user_id'), table_name='custom_pricing')
    op.create_index(op.f('ix_custom_pricing_client_id'), 'custom_pricing', ['client_id'], unique=False)
    op.drop_constraint(op.f('custom_pricing_client_id_fkey'), 'custom_pricing', type_='foreignkey')
    op.drop_constraint(op.f('custom_pricing_requested_by_fkey'), 'custom_pricing', type_='foreignkey')
    op.drop_constraint(op.f('custom_pricing_user_id_fkey'), 'custom_pricing', type_='foreignkey')
    op.create_foreign_key(None, 'custom_pricing', 'users', ['requested_by'], ['id'])
    op.create_foreign_key(None, 'custom_pricing', 'users', ['client_id'], ['id'])
    op.drop_column('custom_pricing', 'user_id')
    op.drop_index(op.f('ix_deliverables_client_id_status'), table_name='deliverables')
    op.alter_column('escalations', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('escalations', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_escalations_status_created_at'), table_name='escalations')
    op.add_column('leave_requests', sa.Column('reviewed_by', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('leave_requests', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('leave_requests', 'reason',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_leave_requests_team_member_id_status'), table_name='leave_requests')
    op.drop_constraint(op.f('leave_requests_approved_by_fkey'), 'leave_requests', type_='foreignkey')
    op.create_foreign_key(None, 'leave_requests', 'users', ['reviewed_by'], ['id'])
    op.drop_column('leave_requests', 'approved_by')
    op.drop_index(op.f('ix_notifications_user_id_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_subscriptions_gateway_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_user_id_status'), table_name='subscriptions')
    op.drop_index(op.f('ux_subscriptions_gateway_subscription_id'), table_name='subscriptions')
    op.add_column('tasks', sa.Column('requested_by', sa.UUID(as_uuid=False), nullable=True))
    op.drop_index(op.f('ix_tasks_assigned_to_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_client_id_status'), table_name='tasks')
    op.create_foreign_key(None, 'tasks', 'users', ['requested_by'], ['id'])
    op.add_column('ticket_messages', sa.Column('file_name', sa.Text(), nullable=True))
    op.add_column('ticket_messages', sa.Column('file_size_bytes', sa.BigInteger(), nullable=True))
    op.add_column('ticket_messages', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.alter_column('ticket_messages', 'message_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('tickets', sa.Column('ticket_number', sa.String(), nullable=False))
    op.add_column('tickets', sa.Column('linked_deliverable_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('tickets', sa.Column('reopened_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index(op.f('ix_tickets_user_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_user_id_status'), table_name='tickets')
    op.create_index(op.f('ix_tickets_client_id'), 'tickets', ['client_id'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_number'), 'tickets', ['ticket_number'], unique=True)
    op.create_foreign_key(None, 'tickets', 'deliverables', ['linked_deliverable_id'], ['id'])
    op.drop_index(op.f('ix_users_auth_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_not_deleted'), table_name='users', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_not_deleted'), 'users', ['id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_auth_id'), 'users', ['auth_id'], unique=False)
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_tickets_ticket_number'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_client_id'), table_name='tickets')
    op.create_index(op.f('ix_tickets_user_id_status'), 'tickets', ['client_id', 'status'], unique=False)
    op.create_index(op.f('ix_tickets_user_id'), 'tickets', ['client_id'], unique=False)
    op.drop_column('tickets', 'updated_at')
    op.drop_column('tickets', 'reopened_at')
    op.drop_column('tickets', 'linked_deliverable_id')
    op.drop_column('tickets', 'ticket_number')
    op.alter_column('ticket_messages', 'message_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('ticket_messages', 'is_read')
    op.drop_column('ticket_messages', 'file_size_bytes')
    op.drop_column('ticket_messages', 'file_name')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_index(op.f('ix_tasks_client_id_status'), 'tasks', ['client_id', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_assigned_to_status'), 'tasks', ['assigned_to', 'status'], unique=False)
    op.drop_column('tasks', 'requested_by')
    op.create_index(op.f('ux_subscriptions_gateway_subscription_id'), 'subscriptions', ['gateway_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_user_id_status'), 'subscriptions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_subscriptions_gateway_subscription_id'), 'subscriptions', ['gateway_subscription_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id_is_read'), 'notifications', ['user_id', 'is_read'], unique=False)
    op.add_column('leave_requests', sa.Column('approved_by', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.create_foreign_key(op.f('leave_requests_approved_by_fkey'), 'leave_requests', 'users', ['approved_by'], ['id'])
    op.create_index(op.f('ix_leave_requests_team_member_id_status'), 'leave_requests', ['team_member_id', 'status'], unique=False)
    op.alter_column('leave_requests', 'reason',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('leave_requests', 'reviewed_at')
    op.drop_column('leave_requests', 'reviewed_by')
    op.create_index(op.f('ix_escalations_status_created_at'), 'escalations', ['status', 'created_at'], unique=False)
    op.alter_column('escalations', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('escalations', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_deliverables_client_id_status'), 'deliverables', ['client_id', 'status'], unique=False)
    op.add_column('custom_pricing', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'custom_pricing', type_='foreignkey')
    op.drop_constraint(None, 'custom_pricing', type_='foreignkey')
    op.create_foreign_key(op.f('custom_pricing_user_id_fkey'), 'custom_pricing', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('custom_pricing_requested_by_fkey'), 'custom_pricing', 'users', ['requested_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('custom_pricing_client_id_fkey'), 'custom_pricing', 'users', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_custom_pricing_client_id'), table_name='custom_pricing')
    op.create_index(op.f('ix_custom_pricing_user_id'), 'custom_pricing', ['user_id'], unique=False)
    op.alter_column('custom_pricing', 'requested_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('custom_pricing', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_content_calendar_client_id_scheduled_date'), 'content_calendar', ['client_id', 'scheduled_date'], unique=False)
    op.add_column('addons', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('addons', sa.Column('payment_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'addons', type_='foreignkey')
    op.create_foreign_key(op.f('addons_user_id_fkey'), 'addons', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_addons_client_id'), table_name='addons')
    op.create_index(op.f('ix_addons_user_id_status'), 'addons', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_addons_user_id'), 'addons', ['user_id'], unique=False)
    op.alter_column('addons', 'gateway',
               existing_type=postgresql.ENUM('razorpay', 'stripe', name='payment_gateway'),
               nullable=True)
    op.drop_column('addons', 'updated_at')
    op.drop_column('addons', 'content_brief')
    op.drop_column('addons', 'gateway_payment_id')
    op.drop_column('addons', 'client_id')
    op.drop_constraint(None, 'addon_pricing', type_='foreignkey')
    op.drop_column('addon_pricing', 'updated_by')
    op.create_table('task_status_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('old_status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('new_status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('changed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], name=op.f('task_status_history_changed_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('task_status_history_task_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('task_status_history_pkey'))
    )
    op.create_index(op.f('ix_task_status_history_task_id'), 'task_status_history', ['task_id'], unique=False)
    op.create_table('questionnaire_audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('questionnaire_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('change_source', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('old_ai_analysis', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_ai_analysis', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('old_summary_line', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('new_summary_line', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('changed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], name=op.f('questionnaire_audit_logs_changed_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], name=op.f('questionnaire_audit_logs_questionnaire_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('questionnaire_audit_logs_pkey'))
    )
    op.create_index(op.f('ix_questionnaire_audit_logs_questionnaire_id'), 'questionnaire_audit_logs', ['questionnaire_id'], unique=False)
    # ### end Alembic commands ###
