"""Add onboarding tracking columns to users

Revision ID: d84988f003c2
Revises: 9ddd8537d7d4
Create Date: 2026-08-10 23:10:04.480254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd84988f003c2'
down_revision: Union[str, Sequence[str], None] = '9ddd8537d7d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('terms_accepted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('onboarding_stage', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_stage')
    op.drop_column('users', 'terms_accepted')
    # ### end Alembic commands ###
